# Defaults: https://github.com/causes/scss-lint/blob/master/config/default.yml
# Wishlist:
#   - No custom colours allowed e.g. `#000`.

exclude: '*.css'

linters:

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#borderzero
  BorderZero:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#bangformat
  BangFormat:
    severity: error
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorkeyword
  ColorKeyword:
    severity: error
    enabled: true
    exclude: "core/_debug.scss"

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#comment
  Comment:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#compass-linters
  Compass::*:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#debugstatement
  DebugStatement:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#declarationorder
  DeclarationOrder:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#duplicateproperty
  DuplicateProperty:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#elseplacement
  ElsePlacement:
    severity: error
    enabled: true
    style: new_line

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptylinebetweenblocks
  EmptyLineBetweenBlocks:
    severity: error
    enabled: true
    ignore_single_line_blocks: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptyrule
  EmptyRule:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#finalnewline
  FinalNewline:
    enabled: false
    present: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexlength
  HexLength:
    enabled: true
    style: short

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexnotation
  HexNotation:
    severity: error
    enabled: true
    style: lowercase

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#idwithextraneousselector
  IdWithExtraneousSelector:
    severity: error
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#importpath
  ImportPath:
    severity: error
    enabled: true
    leading_underscore: false
    filename_extension: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#indentation
  Indentation:
    severity: error
    enabled: true
    character: space
    width: 2

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#leadingzero
  LeadingZero:
    severity: error
    enabled: true
    style: include_zero

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#mergeableselector
  MergeableSelector:
    severity: error
    enabled: true
    force_nesting: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#nameformat
  NameFormat:
    enabled: true
    convention: BEM

















  CapitalizationInSelector:
    enabled: true









  HexValidation:
    enabled: true







  MergeableSelector:
    enabled: true
    force_nesting: true



  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: false
    style: double_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

